<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transfer Funds</name>
   <tag></tag>
   <elementGuidId>8775c4c1-685a-4b01-be72-5fbe517352fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='transfer_funds_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transfer_funds_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>744749d4-94e0-4dda-8e03-0981be52b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headers</value>
      <webElementGuid>8ff35a78-b582-48f0-bee7-ea976ee68a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transfer_funds_link</value>
      <webElementGuid>e4a0d61a-b698-48ba-90a6-ca873c8aefb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Funds</value>
      <webElementGuid>39cc7945-c0d0-4631-baf1-053ac8dbef8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transfer_funds_link&quot;)</value>
      <webElementGuid>338e0643-590d-4837-a78a-f90d221ee0bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='transfer_funds_link']</value>
      <webElementGuid>694c6bf3-c959-41c7-a530-15197a1af75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='online_banking_features']/div[3]/div/h4/span</value>
      <webElementGuid>2d0695eb-784a-4d5e-88f5-7ef9be70bf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checking Account Activity'])[1]/following::span[1]</value>
      <webElementGuid>06cf866d-cbb9-4114-bf52-31baa85ca58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Services'])[1]/following::span[2]</value>
      <webElementGuid>3374b7e5-0edc-4969-937a-69153f5d45b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Money Map'])[1]/preceding::span[1]</value>
      <webElementGuid>58a6d29a-35c3-4f67-865f-76aee5767d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download WebInspect'])[1]/preceding::span[2]</value>
      <webElementGuid>d0b5e788-b4ce-48da-830c-764a9fcfa8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer Funds']/parent::*</value>
      <webElementGuid>6622b89d-379e-481d-a281-99022c6b21a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h4/span</value>
      <webElementGuid>edf288c6-3563-428c-8aa2-43fa07cae78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'transfer_funds_link' and (text() = 'Transfer Funds' or . = 'Transfer Funds')]</value>
      <webElementGuid>c8c044b4-be38-4615-b223-8bd4e1643d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
